<?php

namespace Database\Seeders;

use App\Models\Kendaraan;
use App\Models\Opd;
use Illuminate\Database\Seeder;

class KendaraanSeeder extends Seeder
{
    public function run(): void
    {
        // Pastikan minimal ada 1 OPD di database agar opd_id valid
        $defaultOpd = Opd::first() ?? Opd::create([
            'kode_opd' => 'BPKPD01',
            'nama_opd' => 'BPKPD Kebumen'
        ]);

        $dataKendaraan = [
            [
                'no_urut' => '20',
                'plat_nomor' => 'AA 9537 D',
                'no_stnk' => null,
                'no_bpkb' => '7607411',
                'nomor_rangka' => 'FF172LA-10212',
                'nomor_mesin' => 'H07C-A7111334',
                'merk_tipe' => 'HINO FF172',
                'tahun_pembuatan' => 1987,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_berat',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '25',
                'plat_nomor' => 'AA 6260 1045',
                'no_stnk' => null,
                'no_bpkb' => '8568822',
                'nomor_rangka' => 'HA140 31516',
                'nomor_mesin' => 'HAE-2031370',
                'merk_tipe' => 'HONDA MCB',
                'tahun_pembuatan' => 1989,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_ringan',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '27',
                'plat_nomor' => 'AA 1243 XD',
                'no_stnk' => null,
                'no_bpkb' => '8399525',
                'nomor_rangka' => '4093',
                'nomor_mesin' => '924661',
                'merk_tipe' => 'DAIHATSU MOBIL HILINE F69',
                'tahun_pembuatan' => 1989,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_ringan',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '29',
                'plat_nomor' => 'AA 6951 XW',
                'no_stnk' => null,
                'no_bpkb' => '9150347',
                'nomor_rangka' => 'HA155 43602',
                'nomor_mesin' => 'HAE 2043617',
                'merk_tipe' => 'HONDA MCB',
                'tahun_pembuatan' => 1990,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '34',
                'plat_nomor' => 'AA 8234 XD',
                'no_stnk' => null,
                'no_bpkb' => '9650555',
                'nomor_rangka' => 'KF 50-075390',
                'nomor_mesin' => '5K-9021632',
                'merk_tipe' => 'TOYOTA KF 50',
                'tahun_pembuatan' => 1990,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '45',
                'plat_nomor' => 'AA 9575 AD',
                'no_stnk' => null,
                'no_bpkb' => null,
                'nomor_rangka' => 'V6814482',
                'nomor_mesin' => '18125',
                'merk_tipe' => 'TOYOTA KF 50 PICKUP',
                'tahun_pembuatan' => 1992,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '47',
                'plat_nomor' => 'AA 1650 XD',
                'no_stnk' => null,
                'no_bpkb' => null,
                'nomor_rangka' => 'KF 50-123923',
                'nomor_mesin' => '5K-9129122',
                'merk_tipe' => 'TOYOTA KF 50 PICKUP',
                'tahun_pembuatan' => 1992,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_ringan',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '49',
                'plat_nomor' => 'AA 6139 XM',
                'no_stnk' => null,
                'no_bpkb' => '773405',
                'nomor_rangka' => 'HA21793526',
                'nomor_mesin' => 'HAE2093940',
                'merk_tipe' => 'HONDA MCB',
                'tahun_pembuatan' => 1992,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_berat',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '50',
                'plat_nomor' => 'AA 6466 XM',
                'no_stnk' => null,
                'no_bpkb' => '773406',
                'nomor_rangka' => 'NC25000803',
                'nomor_mesin' => 'NCE1197871',
                'merk_tipe' => 'HONDA C100',
                'tahun_pembuatan' => 1992,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_ringan',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '57',
                'plat_nomor' => 'AA 6261 XW',
                'no_stnk' => null,
                'no_bpkb' => '1503651',
                'nomor_rangka' => 'MH1 HA000PPK 050001',
                'nomor_mesin' => 'HAE.2149669',
                'merk_tipe' => 'HONDA MCB',
                'tahun_pembuatan' => 1993,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_ringan',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '60',
                'plat_nomor' => 'AA 8249 XD',
                'no_stnk' => null,
                'no_bpkb' => '1138439',
                'nomor_rangka' => 'KF 50-141886',
                'nomor_mesin' => 'SK 9170580',
                'merk_tipe' => 'Toyota Kijang KF',
                'tahun_pembuatan' => 1993,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_berat',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'proses_lelang',
            ],
            [
                'no_urut' => '63',
                'plat_nomor' => 'AA 9505 GW',
                'no_stnk' => null,
                'no_bpkb' => null,
                'nomor_rangka' => 'MHF21KF4001163780',
                'nomor_mesin' => '5K-9223887',
                'merk_tipe' => 'TOYOTA KF 40 RV',
                'tahun_pembuatan' => 1994,
                'jumlah_roda' => '4',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '64',
                'plat_nomor' => 'AA 9847 PD',
                'no_stnk' => null,
                'no_bpkb' => '2796295',
                'nomor_rangka' => 'MH1HA000RRK100797',
                'nomor_mesin' => 'HAE 2200404',
                'merk_tipe' => 'Honda MCB MCB',
                'tahun_pembuatan' => 1994,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '68',
                'plat_nomor' => 'AA 9721 KD',
                'no_stnk' => null,
                'no_bpkb' => null,
                'nomor_rangka' => 'MHDA100VXRJ-277080',
                'nomor_mesin' => 'A100-ID-164394',
                'merk_tipe' => 'SUZUKI A100 X',
                'tahun_pembuatan' => 1994,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'baik',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ],
            [
                'no_urut' => '74',
                'plat_nomor' => 'AA 9687 AD',
                'no_stnk' => null,
                'no_bpkb' => '2564811',
                'nomor_rangka' => 'MH33WL003RK105115',
                'nomor_mesin' => '3HB103268',
                'merk_tipe' => 'YAMAHA YT 115',
                'tahun_pembuatan' => 1994,
                'jumlah_roda' => '2',
                'peruntukan' => 'operasional',
                'opd_id' => $defaultOpd->id,
                'status_konfirmasi' => 'diterima',
                'alasan_penolakan' => null,
                'kondisi' => 'rusak_berat',
                'pemegang_kendaraan' => null,
                'nip_pemegang' => null,
                'status_operasional' => 'aktif',
            ]
        ];

        foreach ($dataKendaraan as $data) {
            Kendaraan::updateOrCreate(
                ['plat_nomor' => $data['plat_nomor']],
                $data
            );
        }
    }
}